version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 20
  groups:
    test-dependencies:
      patterns:
      - org.junit.*
      - org.mockito.*
    log4j:
      patterns:
      - org.apache.logging.*
    jackson:
      patterns:
      - com.fasterxml.*
